name: "refresh"

on:
  workflow_dispatch:
  schedule:
    - cron: '10 * * * *'

jobs:
  aptb:
    uses: invalidunit/action/.github/workflows/aptb.yml@main
    with:
      config-path: https://invalidunit.github.io/repo/


  remove_all_old_actions:
    uses: invalidunit/action/.github/workflows/remove_all_actions.yml@main
